from __future__ import annotations

import os
from pathlib import Path
from typing import Any

import pandas as pd

from mekubbal.control import _load_toml_table


def _format_float(value: float) -> str:
    return f"{float(value):.10g}"


def harden_control_config(
    base_config_path: str | Path,
    sweep_report_path: str | Path,
    output_config_path: str | Path,
    *,
    rank: int = 1,
    profile: str = "hardened-defaults",
) -> dict[str, Any]:
    if rank < 1:
        raise ValueError("rank must be >= 1.")

    base_path = Path(base_config_path).resolve()
    if not base_path.exists():
        raise FileNotFoundError(f"Base config does not exist: {base_path}")
    base_raw = _load_toml_table(base_path)
    base_meta = base_raw.get("meta", {})
    if base_meta is not None and not isinstance(base_meta, dict):
        raise ValueError("Base config meta table must be a TOML table when present.")
    base_version = int(base_meta.get("config_version", 1))

    sweep_path = Path(sweep_report_path).resolve()
    if not sweep_path.exists():
        raise FileNotFoundError(f"Sweep report does not exist: {sweep_path}")
    sweep = pd.read_csv(sweep_path)
    required = {"downside_penalty", "drawdown_penalty", "v2_minus_v1_like_avg_equity_gap"}
    missing = sorted(required - set(sweep.columns))
    if missing:
        raise ValueError(f"Sweep report missing required columns: {missing}")
    if len(sweep) < rank:
        raise ValueError(f"Requested rank {rank} but sweep report has only {len(sweep)} rows.")

    sort_columns: list[str] = []
    ascending: list[bool] = []
    if "regime_tie_break_band" in sweep.columns:
        sort_columns.append("regime_tie_break_band")
        ascending.append(True)
    for column, is_ascending in [
        ("v2_avg_diag_turbulent_max_drawdown", True),
        ("v2_avg_diag_turbulent_win_rate", False),
        ("v2_avg_diag_turbulent_equity_factor", False),
        ("v2_avg_diag_max_drawdown", True),
    ]:
        if column in sweep.columns:
            sort_columns.append(column)
            ascending.append(is_ascending)
    sort_columns.append("v2_minus_v1_like_avg_equity_gap")
    ascending.append(False)

    ranked = sweep.sort_values(sort_columns, ascending=ascending).reset_index(drop=True)
    selected = ranked.iloc[rank - 1]
    downside_penalty = float(selected["downside_penalty"])
    drawdown_penalty = float(selected["drawdown_penalty"])
    selected_delta = float(selected["v2_minus_v1_like_avg_equity_gap"])

    output = Path(output_config_path).resolve()
    output.parent.mkdir(parents=True, exist_ok=True)
    extends_rel = Path(os.path.relpath(base_path, start=output.parent)).as_posix()
    next_version = max(base_version + 1, 1)

    lines = [
        "# Generated by mekubbal-harden-config",
        "",
        "[meta]",
        f'extends = "{extends_rel}"',
        f"config_version = {next_version}",
        f'profile = "{profile}"',
        f'source_sweep_report = "{sweep_path.as_posix()}"',
        f"selected_rank = {rank}",
        f"selected_delta = {_format_float(selected_delta)}",
        "",
        "[ablation]",
        f"v2_downside_penalty = {_format_float(downside_penalty)}",
        f"v2_drawdown_penalty = {_format_float(drawdown_penalty)}",
        "",
        "[sweep]",
        f"downside_grid = [{_format_float(downside_penalty)}]",
        f"drawdown_grid = [{_format_float(drawdown_penalty)}]",
        "",
    ]
    output.write_text("\n".join(lines), encoding="utf-8")

    return {
        "output_config_path": str(output),
        "base_config_path": str(base_path),
        "selected_rank": rank,
        "selected_delta": selected_delta,
        "selected_downside_penalty": downside_penalty,
        "selected_drawdown_penalty": drawdown_penalty,
        "config_version": next_version,
    }
