from __future__ import annotations

from copy import deepcopy
from pathlib import Path
from typing import Any

from mekubbal.profile.config import resolve_existing_path
from mekubbal.profile.shadow import _resolve_relative_to


def prepare_schedule_matrix_context(
    *,
    schedule_cfg: dict[str, Any],
    shadow_cfg: dict[str, Any],
    config_dir_path: Path,
    matrix_config_override: dict[str, Any] | None,
    matrix_config_dir: str | Path | None,
    matrix_config_label: str | None,
    load_profile_matrix_config_fn: Any,
    run_profile_matrix_fn: Any,
    run_profile_matrix_config_fn: Any,
) -> dict[str, Any]:
    matrix_config_path = resolve_existing_path(config_dir_path, str(schedule_cfg["matrix_config"]))
    symbols = list(schedule_cfg["symbols"])
    shadow_enabled = bool(shadow_cfg.get("enabled", False))
    shadow_selection_state_path: Path | None = None
    production_selection_state_path: Path | None = None
    matrix_call_kwargs: dict[str, Any] = {
        "symbols_override": symbols if symbols else None,
    }
    resolved_matrix_config_dir = (
        Path(matrix_config_dir).resolve() if matrix_config_dir is not None else matrix_config_path.parent
    )
    resolved_matrix_config_label = matrix_config_label or str(matrix_config_path)
    matrix_runtime_config = (
        deepcopy(matrix_config_override)
        if matrix_config_override is not None
        else load_profile_matrix_config_fn(matrix_config_path)
    )

    if shadow_enabled:
        matrix_loaded = deepcopy(matrix_runtime_config)
        matrix_output_root_hint = _resolve_relative_to(
            resolved_matrix_config_dir, str(matrix_loaded["matrix"]["output_root"])
        )
        matrix_promotion_cfg = dict(matrix_loaded["promotion"])
        production_state_raw = str(shadow_cfg.get("production_state_path", "")).strip()
        if production_state_raw:
            production_selection_state_path = _resolve_relative_to(matrix_output_root_hint, production_state_raw)
        else:
            production_selection_state_path = _resolve_relative_to(
                matrix_output_root_hint, str(matrix_promotion_cfg["state_path"])
            )
        if not production_selection_state_path.exists():
            raise FileNotFoundError(
                f"Shadow evaluation requires existing production state: {production_selection_state_path}"
            )
        shadow_selection_state_path = _resolve_relative_to(
            matrix_output_root_hint, str(shadow_cfg["shadow_state_path"])
        )
        matrix_call_kwargs["promotion_override"] = {
            "enabled": True,
            "state_path": str(shadow_selection_state_path),
        }

    if (
        matrix_config_override is None
        and matrix_config_dir is None
        and matrix_config_label is None
    ):
        matrix_summary = run_profile_matrix_fn(
            matrix_config_path,
            **matrix_call_kwargs,
        )
    else:
        matrix_summary = run_profile_matrix_config_fn(
            matrix_runtime_config,
            config_dir=resolved_matrix_config_dir,
            config_label=resolved_matrix_config_label,
            **matrix_call_kwargs,
        )
    matrix_output_root = Path(str(matrix_summary["output_root"])).resolve()

    if shadow_enabled:
        assert production_selection_state_path is not None
        assert shadow_selection_state_path is not None
        production_selection_state_path = _resolve_relative_to(
            matrix_output_root, str(production_selection_state_path)
        )
        shadow_selection_state_path = _resolve_relative_to(matrix_output_root, str(shadow_selection_state_path))
        if not shadow_selection_state_path.exists():
            profile_selection = matrix_summary.get("profile_selection")
            if isinstance(profile_selection, dict) and profile_selection.get("state_path"):
                shadow_selection_state_path = Path(str(profile_selection["state_path"])).resolve()
        if not shadow_selection_state_path.exists():
            raise ValueError(
                "Shadow evaluation enabled but shadow selection state was not generated by profile matrix."
            )

    selection_state_path = None
    if shadow_enabled:
        selection_state_path = production_selection_state_path
    else:
        profile_selection = matrix_summary.get("profile_selection")
        if isinstance(profile_selection, dict) and profile_selection.get("state_path"):
            selection_state_path = Path(str(profile_selection["state_path"])).resolve()
        else:
            fallback_state = matrix_output_root / "reports" / "profile_selection_state.json"
            if fallback_state.exists():
                selection_state_path = fallback_state
    if selection_state_path is None:
        raise ValueError(
            "Profile selection state not found. Enable promotion in profile-matrix config "
            "or run mekubbal-profile-select before schedule monitoring."
        )

    return {
        "matrix_summary": matrix_summary,
        "matrix_output_root": matrix_output_root,
        "selection_state_path": Path(selection_state_path).resolve(),
        "shadow_selection_state_path": (
            Path(shadow_selection_state_path).resolve() if shadow_selection_state_path is not None else None
        ),
    }
